### ISSUE TITLE
Is it an correct implementation of GetHashCode function in this case?

### ISSUE THREAD

**Issue by Ky7m** [akkadotnet/akka.net#2706]
Looking through code I found two interesting lines:
https://github.com/akkadotnet/akka.net/blob/v1.3/src/contrib/cluster/Akka.DistributedData/Replicator.Messages.cs#L458
https://github.com/akkadotnet/akka.net/blob/v1.3/src/contrib/cluster/Akka.DistributedData/Replicator.Messages.cs#L203
they look a bit different from regular GetHashCode implementation across solution (e.g. https://github.com/akkadotnet/akka.net/blob/v1.3/src/contrib/cluster/Akka.DistributedData/Replicator.Messages.cs#L255)
It seems to me that it works in different way than it is expected. Priority of the "??" operator is lower than priority of other operators.
I guess that correct version might be 
` return (Key.GetHashCode() * 397) ^ (Data?.GetHashCode() ?? 0);` // <--- surround with **()** 
instead of actual version
` return (Key.GetHashCode() * 397) ^ Data?.GetHashCode() ?? 0;`

**Comment by Aaronontheweb** [comment]
cc @Horusiath - was this generated automatically via R#?

**Comment by Aaronontheweb** [comment]
@Ky7m did you close this because you think the issue is resolved? Just asking!

**Comment by Ky7m** [comment]
@Aaronontheweb, I am still not sure about this implementation, but it was open for more than 1 year :) so I decided to close it.
