### ISSUE TITLE
TeamCity build agents fail to clean checkout directory due to locked .dlls in long-running spec

### ISSUE THREAD

**Issue by heynickc** [akkadotnet/akka.net#2848]
Intermittent issue with the TeamCity build agent preparing to run a build.  When it attempts to clean the checkout directory, it's unable to delete all of the files due to what seems to be a process locking them.  Looks like these files are related to .dlls downloaded to the `.dotnet` folder on the server which are added when we run `dotnet-install.ps1` to download the .NET CLI v1.0.4.

```
[10:35:16]Clean build enabled: removing old files from D:\work\edbce350daf6a08d
[10:35:17]Failed to delete empty directory: D:\work\edbce350daf6a08d\src\contrib\cluster\Akka.DistributedData.LightningDB
[10:35:17]Failed to delete empty directory: D:\work\edbce350daf6a08d\src\core\Akka.TestKit
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\dotnet.exe
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\MSBuild.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\Microsoft.Build.Framework.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\Microsoft.Build.Tasks.Core.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\Microsoft.Build.Utilities.Core.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\Microsoft.Build.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\Microsoft.DotNet.PlatformAbstractions.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\Microsoft.Extensions.DependencyModel.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\Newtonsoft.Json.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\NuGet.Common.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\NuGet.Configuration.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\NuGet.Frameworks.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\NuGet.LibraryModel.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\NuGet.Packaging.Core.Types.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\NuGet.Packaging.Core.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\NuGet.Packaging.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\NuGet.ProjectModel.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\NuGet.RuntimeModel.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\NuGet.Versioning.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\System.Collections.Immutable.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\System.Collections.NonGeneric.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\System.Diagnostics.StackTrace.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\System.Reflection.Metadata.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\System.Runtime.Serialization.Primitives.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\System.Xml.XmlDocument.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\runtimes\win\lib\netstandard1.3\System.Diagnostics.FileVersionInfo.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\sdk\1.0.4\runtimes\win\lib\netstandard1.3\System.IO.Pipes.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\Microsoft.DiaSymReader.Native.amd64.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Collections.Concurrent.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Collections.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Console.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Diagnostics.Debug.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Diagnostics.Process.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Diagnostics.Tracing.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Dynamic.Runtime.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Globalization.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.IO.FileSystem.Primitives.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.IO.FileSystem.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.IO.MemoryMappedFiles.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.IO.UnmanagedMemoryStream.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.IO.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Linq.Expressions.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Linq.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.ObjectModel.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Private.CoreLib.ni.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Private.Uri.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Reflection.Emit.ILGeneration.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Reflection.Emit.Lightweight.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Reflection.Extensions.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Reflection.Primitives.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Reflection.TypeExtensions.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Reflection.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Resources.ResourceManager.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Runtime.Extensions.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Runtime.Handles.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Runtime.InteropServices.RuntimeInformation.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Runtime.InteropServices.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Runtime.Loader.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Runtime.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Security.Claims.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Security.Cryptography.Algorithms.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Security.Cryptography.Primitives.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Security.Principal.Windows.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Security.Principal.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Text.Encoding.Extensions.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Text.Encoding.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Text.RegularExpressions.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Threading.Tasks.Dataflow.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Threading.Tasks.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Threading.Thread.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Threading.ThreadPool.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Threading.Timer.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Threading.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Xml.ReaderWriter.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\System.Xml.XDocument.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\clrjit.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\coreclr.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\hostpolicy.dll
[10:35:17]Failed to delete file: D:\work\edbce350daf6a08d\.dotnet\shared\Microsoft.NETCore.App\1.1.2\mscorlib.dll
[10:35:17]Failed to clean files from: D:\work\edbce350daf6a08d
[10:35:17]
jetbrains.buildServer.RunBuildException: Failed to clean files from: D:\work\edbce350daf6a08d
	at jetbrains.buildServer.agent.impl.buildStages.startStages.CleanBuildCheckoutDirectoryIfNeededStage$1.logFailedToCleanEntireFolder(CleanBuildCheckoutDirectoryIfNeededStage.java:40)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.DirectoryCleanerStage$1.logFailedToCleanEntireFolder(DirectoryCleanerStage.java:58)
	at jetbrains.buildServer.agent.impl.directories.SmartDirectoryCleanerImpl.cleanFolder(SmartDirectoryCleanerImpl.java:67)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.DirectoryCleanerStage.doBuildStage(DirectoryCleanerStage.java:29)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:78)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:37)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:75)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:55)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:297)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:55)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:261)
	at java.lang.Thread.run(Thread.java:745)
[10:35:17]Publishing internal artifacts
```
Once there is a failure to clean the checkout directory, all subsequent builds on that specific build agent have the same issue, indicating that the process isn't being killed properly.

Possible solution is to use FAKE's ProcessHelper to 
kill all processes created by FAKE so that the usage of the .NET CLI by build.fsx is killed regardless of the success/failure of the build:

https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/ProcessHelper.fs#L522:
```
/// Kills all processes that are created by the FAKE build script unless "donotkill" flag was set.
let killAllCreatedProcesses() =
...
```

**Comment by heynickc** [comment]
Issue still occurring today.  
```
Failed to start build #4785 in branch 2844 at 13 Jul 17 00:18 on PBW3838
Snapshot dependency failure
View build results »Failed to start build #4758 in branch 2849 at 11 Jul 17 15:50 on PBW3817
Snapshot dependency failure
View build results »Failed to start build #4740 in branch 2840 at 10 Jul 17 12:50 on PBW3786
Snapshot dependency failure
View build results »Failed to start build #4787 in branch 2767 at 13 Jul 17 11:34 on PBW3842
Snapshot dependency "... Akka.NET Windows MultiNodeTests" failed
View build results »Failed to start build #4787 in branch 2767 at 13 Jul 17 11:34 on PBW3842
Snapshot dependency "... Akka.NET Windows Performance Tests" failed
View build results »Failed to start build #4788 in branch 2816 at 13 Jul 17 11:43 on PBW3843
Snapshot dependency "... Akka.NET Windows MultiNodeTests" failed
View build results »Failed to start build #4788 in branch 2816 at 13 Jul 17 11:43 on PBW3843
Snapshot dependency "... Akka.NET Windows Performance Tests" failed
View build results »Failed to start build #4788 in branch 2816 at 13 Jul 17 11:43 on PBW3843
Snapshot dependency "... Akka.NET Windows Unit Tests (.NET Core)" failed
View build results »Failed to start build #4789 in branch 2836 at 13 Jul 17 11:59 on PBW3843
Snapshot dependency "... Akka.NET Windows MultiNodeTests" failed
View build results »Failed to start build #4789 in branch 2836 at 13 Jul 17 11:59 on PBW3843
Snapshot dependency "... Akka.NET Windows Performance Tests" failed
View build results »Failed to start build #4789 in branch 2836 at 13 Jul 17 11:59 on PBW3843
Snapshot dependency "... Akka.NET Windows Unit Tests (.NET Core)" failed
```
I have restarted the affected branches and am going to be gathering more log data and information about the root cause.

**Comment by heynickc** [comment]
The list of files that can't be cleaned points to an issue with `dotnet xunit`

```
[14:13:21]Failed to delete file: D:\work\edbce350daf6a08d\src\core\Akka.Remote.TestKit.Tests\bin\Release\net452\Akka.Remote.TestKit.Tests.dll
[14:13:21]Failed to delete file: D:\work\edbce350daf6a08d\src\core\Akka.Remote.TestKit.Tests\bin\Release\net452\Akka.TestKit.Xunit2.dll
[14:13:21]Failed to delete file: D:\work\edbce350daf6a08d\src\core\Akka.Remote.TestKit.Tests\bin\Release\net452\Akka.TestKit.dll
[14:13:21]Failed to delete file: D:\work\edbce350daf6a08d\src\core\Akka.Remote.TestKit.Tests\bin\Release\net452\Akka.Tests.Shared.Internals.dll
[14:13:21]Failed to delete file: D:\work\edbce350daf6a08d\src\core\Akka.Remote.TestKit.Tests\bin\Release\net452\Akka.dll
[14:13:21]Failed to delete file: D:\work\edbce350daf6a08d\src\core\Akka.Remote.TestKit.Tests\bin\Release\net452\DotNetty.Common.dll
[14:13:21]Failed to delete file: D:\work\edbce350daf6a08d\src\core\Akka.Remote.TestKit.Tests\bin\Release\net452\DotNetty.Transport.dll
[14:13:21]Failed to clean files from: D:\work\edbce350daf6a08d
```

Within the same time, this spec fails:

```
[Test collection for Akka.Remote.TestKit.Tests.RemoteConnectionSpecs (1)] Akka.Remote.TestKit.Tests.RemoteConnectionSpecs.RemoteConnection_should_send_and_decode_messages (29m:39s)
[08:04:02][RunTests] Running build failed.
[08:04:02][RunTests] Error:
[08:04:02][RunTests] System.Exception: Process dotnet xunit -f net452 -c Release -nobuild -parallel none -teamcity -xml D:\work\edbce350daf6a08d\TestResults\Akka.Remote.TestKit.Tests_xunit.xml timed out.
[08:04:02][RunTests]    at Fake.ProcessHelper.ExecProcessWithLambdas@104-22.Invoke(String message) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 104
[08:04:02][RunTests]    at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 104
[08:04:02][RunTests]    at FSI_0005.Build.runSingleProject@104.Invoke(String project)
[08:04:02][RunTests]    at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
[08:04:02][RunTests]    at FSI_0005.Build.clo@92-7.Invoke(Unit _arg1)
[08:04:02][RunTests]    at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626`
```

This points to the root cause being that when the `dotnet xunit...` timeout of 30 minutes is hit, the process is not killed.  It is also possible that the initial fix of adding FAKE's `killAllCreatedProcesses()` isn't killing the `dotnet.exe` process.

The timing out spec needs to be addressed, but more importantly the failure to kill the `dotnet xunit` process after the 30 minute timeout needs to be addressed.  This will mean searching for all `dotnet.exe` processes and forcefully killing them when the timeout occurs.

**Comment by heynickc** [comment]
Referencing https://github.com/xunit/xunit/issues/1338 as this is the behavior that we are seeing as well, with the potential that the process `xunit.console.exe` is not killed when `dotnet xunit` is killed

**Comment by heynickc** [comment]
Steps to reproduce:
```
[Fact]
public async Task RemoteConnection_should_send_and_decode_messages()
{
    Thread.Sleep(TimeSpan.FromMinutes(1));
}
```
Set timeout of test process to `1.`:
```
      let result = ExecProcess(fun info ->
            info.FileName <- "dotnet"
            info.WorkingDirectory <- (Directory.GetParent project).FullName
            info.Arguments <- (sprintf "xunit -f net452 -c Release -parallel none -class Akka.Remote.TestKit.Tests.RemoteConnectionSpecs -xml %s_xunit.xml" (outputTests @@ fileNameWithoutExt project))) (TimeSpan.FromMinutes 1.)
```
Build fails, exits, then `xunit.console.exe` writes to stdout on its own accord:
```
xUnit.net Console Runner (64-bit Desktop .NET 4.0.30319.42000)
  Discovering: Akka.Remote.TestKit.Tests
  Discovered:  Akka.Remote.TestKit.Tests
  Starting:    Akka.Remote.TestKit.Tests
    Akka.Remote.TestKit.Tests.RemoteConnectionSpecs.RemoteConnection_should_send_and_decode_Done_message [SKIP]
      This causes a deadlock sometimes
Running build failed.
Error:
System.Exception: Process dotnet xunit -f net452 -c Release -parallel none -class Akka.Remote.TestKit.Tests.RemoteConnectionSpecs -xml C:\Users\nickc\Documents\Projects\akka.net\TestResults\Akka.Remote.TestKit.Tests_xunit.xml timed out.
   at Fake.ProcessHelper.ExecProcessWithLambdas@104-22.Invoke(String message) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 104
   at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 104
   at FSI_0005.Build.runSingleProject@107.Invoke(String project)
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at FSI_0005.Build.clo@94-7.Invoke(Unit _arg1)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
Starting FinalTarget: KillCreatedProcesses
The following processes were started during FAKE step...
46008,
Killing processes started by FAKE...
dotnet
xunit.console

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target                 Duration
------                 --------
KillCreatedProcesses   00:00:00.3419031
RunTests               Failure
Total:                 00:01:01.6173144
---------------------------------------------------------------------
Status:                Failure
---------------------------------------------------------------------
---------------------------------------------------------------------
  1) System.Exception: Process dotnet xunit -f net452 -c Release -parallel none -class Akka.Remote.TestKit.Tests.RemoteConnectionSpecs -xml C:\Users\nickc\Documents\Projects\akka.net\TestResults\Akka.Remote.TestKit.Tests_xunit.xml timed out.
   at Fake.ProcessHelper.ExecProcessWithLambdas@104-22.Invoke(String message) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 104
   at Fake.ProcessHelper.ExecProcessWithLambdas(FSharpFunc`2 configProcessStartInfoF, TimeSpan timeOut, Boolean silent, FSharpFunc`2 errorF, FSharpFunc`2 messageF) in C:\code\fake\src\app\FakeLib\ProcessHelper.fs:line 104
   at FSI_0005.Build.runSingleProject@107.Invoke(String project)
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
   at FSI_0005.Build.clo@94-7.Invoke(Unit _arg1)
   at Fake.TargetHelper.runSingleTarget(TargetTemplate`1 target) in C:\code\fake\src\app\FakeLib\TargetHelper.fs:line 626
---------------------------------------------------------------------

...\akka.net [file-lock-bugfix +0 ~2 -0 !]>   Finished:    Akka.Remote.TestKit.Tests
=== TEST EXECUTION SUMMARY ===
   Akka.Remote.TestKit.Tests  Total: 2, Errors: 0, Failed: 0, Skipped: 1, Time: 61.599s
```
And this verifies that the processes are still running even after calling `killAllCreatedProcesses()` in FAKE:
```
FinalTarget "KillCreatedProcesses" (fun _ ->
    log "Killing processes started by FAKE:"
    startedProcesses |> Seq.iter (fun (pid, _) -> logf "%i, " pid)
    killAllCreatedProcesses()
    log "These processes are still running:"
    getProcessesByName "dotnet" |> Seq.iter (fun x -> log x.ProcessName)
    getProcessesByName "xunit.console" |>Seq.iter (fun x -> log x.ProcessName)
)
```
Returns:
```
Starting FinalTarget: KillCreatedProcesses
Killing processes started by FAKE:
39508
These processes are still running:
dotnet
xunit.console
```

**Comment by heynickc** [comment]
Also confirmed in Task Manager that the process `xunit.console.runner.exe` continues to run after the main `dotnet` process exits.

**Comment by Aaronontheweb** [comment]
Resolved via #2867

**Comment by matkoch** [comment]
We are still getting this: https://teamcity.jetbrains.com/viewLog.html?buildId=1559648&buildTypeId=matkoch_NukeBuild_Nuke&tab=buildLog

Build script is invoked like here: https://github.com/nuke-build/nuke/blob/develop/build.ps1

Could you reopen, or should I create a new issue?
