### ISSUE TITLE
Calling ActorSystem.Dispose hangs indefinitely 

### ISSUE THREAD

**Issue by huzaifak** [akkadotnet/akka.net#4303]
Akka 1.4 RC1
Windows 10, .Net 4.7

Any node in Akka cluster that calls ActorSystem.Dispose hangs indefinitely. This only happens if the node is part of the cluster. If actor system is started as a standalone there is no issue with shutdown process.

The below is logged during the shutdown process.
2020-03-05 16:47:54.9167 Cluster (akka://TestActorSystem) Cluster Node [akka.tcp://TestActorSystem@laxqax-mtir1001.somedomain.com:9901] - Shutting down myself
2020-03-05 16:47:54.9167 Cluster (akka://TestActorSystem) Cluster Node [akka.tcp://TestActorSystem@laxqax-mtir1001.somedomain.com:9901] - Shutting down...
2020-03-05 16:47:54.9167 Cluster (akka://TestActorSystem) Cluster Node [akka.tcp://TestActorSystem@laxqax-mtir1001.somedomain.com:9901] - Successfully shut down
2020-03-05 16:47:59.9953 Akka.Actor.CoordinatedShutdown Coordinated shutdown phase [cluster-shutdown] timed out after 00:00:05
2020-03-05 16:47:59.9953 Akka.Remote.RemoteActorRefProvider+RemotingTerminator Shutting down remote daemon.
2020-03-05 16:48:00.0109 Akka.Remote.RemoteActorRefProvider+RemotingTerminator Remote daemon shut down; proceeding with flushing remote transports.
2020-03-05 16:48:00.0266 Akka.Remote.ReliableDeliverySupervisor Removing receive buffers for [akka.tcp://TestActorSystem@laxqax-mtir1001.somedomain.com:9901]->[akka.tcp://TestActorSystem@test-machine.somedomain.com:9901]
2020-03-05 16:48:00.0734 remoting (akka://TestActorSystem) Remoting shut down
2020-03-05 16:48:00.0734 Akka.Remote.RemoteActorRefProvider+RemotingTerminator Remoting shut down.

**Comment by Aaronontheweb** [comment]
Can verify this is resolved in Akka.NET 1.4.1-RC2/3.

**Comment by huzaifak** [comment]
We upgraded to 1.4.1 and still seeing the issue, below logs.


[DEBUG][03/11/2020 20:26:18][Thread 0001][EventStream] subscribing [akka://JobDispatcherSystem/system/log1-NLogLogger#1089268832] to channel Akka.Event.Debug
[DEBUG][03/11/2020 20:26:18][Thread 0001][EventStream] subscribing [akka://JobDispatcherSystem/system/log1-NLogLogger#1089268832] to channel Akka.Event.Info
[DEBUG][03/11/2020 20:26:18][Thread 0001][EventStream] subscribing [akka://JobDispatcherSystem/system/log1-NLogLogger#1089268832] to channel Akka.Event.Warning
[DEBUG][03/11/2020 20:26:18][Thread 0001][EventStream] subscribing [akka://JobDispatcherSystem/system/log1-NLogLogger#1089268832] to channel Akka.Event.Error
[DEBUG][03/11/2020 20:26:18][Thread 0001][EventStream(JobDispatcherSystem)] Logger log1-NLogLogger [NLogLogger] started
[DEBUG][03/11/2020 20:26:18][Thread 0001][EventStream] subscribing [akka://JobDispatcherSystem/system/UnhandledMessageForwarder#703313591] to channel Akka.Event.UnhandledMessage
[DEBUG][03/11/2020 20:26:18][Thread 0006][akka://JobDispatcherSystem/system] now supervising akka://JobDispatcherSystem/system/UnhandledMessageForwarder
[DEBUG][03/11/2020 20:26:18][Thread 0013][akka://JobDispatcherSystem/system/UnhandledMessageForwarder] Started (Akka.Event.LoggingBus+UnhandledMessageForwarder)
[DEBUG][03/11/2020 20:26:18][Thread 0001][EventStream(JobDispatcherSystem)] StandardOutLogger being removed
[DEBUG][03/11/2020 20:26:18][Thread 0001][EventStream] unsubscribing [akka://all-systems/] from all channels
[DEBUG][03/11/2020 20:27:28][Thread 0045][EventStream] subscribing [akka://all-systems/] to channel Akka.Event.Debug
[DEBUG][03/11/2020 20:27:28][Thread 0045][EventStream] subscribing [akka://all-systems/] to channel Akka.Event.Info
[DEBUG][03/11/2020 20:27:28][Thread 0045][EventStream] subscribing [akka://all-systems/] to channel Akka.Event.Warning
[DEBUG][03/11/2020 20:27:28][Thread 0045][EventStream] subscribing [akka://all-systems/] to channel Akka.Event.Error
[DEBUG][03/11/2020 20:27:28][Thread 0045][EventStream] Shutting down: StandardOutLogger started
[DEBUG][03/11/2020 20:27:28][Thread 0045][EventStream] unsubscribing [akka://JobDispatcherSystem/system/log1-NLogLogger#1089268832] from all channels
[DEBUG][03/11/2020 20:27:28][Thread 0017][akka://JobDispatcherSystem/system/remoting-terminator] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0045][EventStream] All default loggers stopped
[DEBUG][03/11/2020 20:27:07][Thread 0046][akka://JobDispatcherSystem/system/distributedPubSubMediator/JobEvent] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0051][akka://JobDispatcherSystem/system/EventStreamUnsubscriber-1] Stopped
[DEBUG][03/11/2020 20:27:07][Thread 0051][akka://JobDispatcherSystem/user/CoreSingletonManagerProxy] Stopped
[DEBUG][03/11/2020 20:27:07][Thread 0037][akka://JobDispatcherSystem/system/cluster/core/daemon/heartbeatSender] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0019][akka://JobDispatcherSystem/system/remote-deployment-watcher] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0048][akka://JobDispatcherSystem/system/UnhandledMessageForwarder] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0047][akka://JobDispatcherSystem/system/transports] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0050][akka://JobDispatcherSystem/system/remote-watcher] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0045][akka://JobDispatcherSystem/system] Stopping
[DEBUG][03/11/2020 20:27:28][Thread 0018][akka://JobDispatcherSystem/system/endpointManager] Stopped
[DEBUG][03/11/2020 20:27:09][Thread 0049][akka://JobDispatcherSystem/user/notification-sender-router-pool/c7] no longer watched by [akka://JobDispatcherSystem/user/notification-sender-router-pool#1489572681]
[DEBUG][03/11/2020 20:27:09][Thread 0049][akka://JobDispatcherSystem/user/notification-sender-router-pool/c7] received AutoReceiveMessage <PoisonPill>
[DEBUG][03/11/2020 20:27:09][Thread 0052][akka://JobDispatcherSystem/user/notification-sender-router-pool/c8] no longer watched by [akka://JobDispatcherSystem/user/notification-sender-router-pool#1489572681]
[DEBUG][03/11/2020 20:27:09][Thread 0052][akka://JobDispatcherSystem/user/notification-sender-router-pool/c8] received AutoReceiveMessage <PoisonPill>
[DEBUG][03/11/2020 20:27:09][Thread 0049][akka://JobDispatcherSystem/user/notification-sender-router-pool/c7] Stopped
[DEBUG][03/11/2020 20:27:09][Thread 0052][akka://JobDispatcherSystem/user/notification-sender-router-pool/c8] Stopped
[DEBUG][03/11/2020 20:27:09][Thread 0048][akka://JobDispatcherSystem/system/distributedPubSubMediator/SystemEvent] no longer watched by [akka://JobDispatcherSystem/system/distributedPubSubMediator#2060961949]
[DEBUG][03/11/2020 20:27:09][Thread 0045][akka://JobDispatcherSystem/user/$b] no longer watched by [akka://JobDispatcherSystem/system/distributedPubSubMediator/JobEvent#1217610787]
[DEBUG][03/11/2020 20:27:09][Thread 0045][akka://JobDispatcherSystem/user/$a] no longer watched by [akka://JobDispatcherSystem/system/distributedPubSubMediator/SystemEvent#800320859]
[DEBUG][03/11/2020 20:27:09][Thread 0048][akka://JobDispatcherSystem/system/distributedPubSubMediator/SystemEvent] Stopped
[DEBUG][03/11/2020 20:27:09][Thread 0045][akka://JobDispatcherSystem/system/distributedPubSubMediator] Stopped
[DEBUG][03/11/2020 20:27:09][Thread 0027][akka://JobDispatcherSystem/system/cluster/core/publisher] Stopped
[DEBUG][03/11/2020 20:27:09][Thread 0046][EventStream] unsubscribing [akka://JobDispatcherSystem/system/cluster/core/daemon#1590573872] from all channels
[DEBUG][03/11/2020 20:27:09][Thread 0046][akka://JobDispatcherSystem/system/cluster/core/daemon] Stopped
[DEBUG][03/11/2020 20:27:09][Thread 0027][akka://JobDispatcherSystem/system/cluster/core] Stopped
[DEBUG][03/11/2020 20:27:09][Thread 0051][akka://JobDispatcherSystem/user/$c] no longer watched by [akka://JobDispatcherSystem/user/ddataReplicator#1182608165]
[DEBUG][03/11/2020 20:27:09][Thread 0029][akka://JobDispatcherSystem/user/ddataReplicator] Stopped
[WARNING][03/11/2020 20:27:13][Thread 0017][remoting (akka://JobDispatcherSystem)] Association to [akka.tcp://JobDispatcherSystem@laxmtir01.office.cyberu.com:9901] having UID [409036480] is irrecoverably failed. UID is now quarantined and all messages to this UID will be delivered to dead letters. Remote actorsystem must be restarted to recover from this situation.
[DEBUG][03/11/2020 20:27:13][Thread 0018][akka://JobDispatcherSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobDispatcherSystem%40laxmtir01.somedomain.com%3A9901-10/endpointWriter] no longer watched by [akka://JobDispatcherSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobDispatcherSystem%40laxmtir01.somedomain.com%3A9901-10#1708523824]
[DEBUG][03/11/2020 20:27:13][Thread 0020][akka://JobDispatcherSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobDispatcherSystem%40laxmtir01.somedomain.com%3A9901-10] Stopping
[DEBUG][03/11/2020 20:27:13][Thread 0020][akka://JobDispatcherSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobDispatcherSystem%40laxmtir01.somedomain.com%3A9901-10/endpointWriter] Stopping
[DEBUG][03/11/2020 20:27:13][Thread 0020][akka://JobDispatcherSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobDispatcherSystem%40laxmtir01.somedomain.com%3A9901-10/endpointWriter/endpointReader-akka.tcp%3A%2F%2FJobDispatcherSystem%40laxmtir01.somedomain.com%3A9901-1] no longer watched by [akka://JobDispatcherSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobDispatcherSystem%40laxmtir01.somedomain.com%3A9901-10/endpointWriter#1144814083]
[DEBUG][03/11/2020 20:27:13][Thread 0020][akka://JobDispatcherSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobDispatcherSystem%40laxmtir01.somedomain.com%3A9901-10/endpointWriter/endpointReader-akka.tcp%3A%2F%2FJobDispatcherSystem%40laxmtir01.somedomain.com%3A9901-1] Stopped
[DEBUG][03/11/2020 20:27:13][Thread 0020][akka.tcp://JobDispatcherSystem@laxmtir02.somedomain.com:9901/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobDispatcherSystem%40laxmtir01.somedomain.com%3A9901-10/endpointWriter] Disassociated [akka.tcp://JobDispatcherSystem@laxmtir02.somedomain.com:9901] -> akka.tcp://JobDispatcherSystem@laxmtir01.somedomain.com:9901
[DEBUG][03/11/2020 20:27:13][Thread 0020][akka://JobDispatcherSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobDispatcherSystem%40laxmtir01.somedomain.com%3A9901-10/endpointWriter] Stopped
[INFO][03/11/2020 20:27:13][Thread 0017][akka.tcp://JobDispatcherSystem@laxmtir02.somedomain.com:9901/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobDispatcherSystem%40laxmtir01.somedomain.com%3A9901-10] Removing receive buffers for [akka.tcp://JobDispatcherSystem@laxmtir02.somedomain.com:9901]->[akka.tcp://JobDispatcherSystem@laxmtir01.somedomain.com:9901]
[DEBUG][03/11/2020 20:27:13][Thread 0020][akka.tcp://JobDispatcherSystem@laxmtir02.somedomain.com:9901/system/transports/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3A%2F%2FJobDispatcherSystem%40laxmtir01.somedomain.com%3A9901-10] Association between local [tcp://JobDispatcherSystem@0.0.0.0:57152] and remote [tcp://JobDispatcherSystem@laxmtir01.somedomain.com:9901] was disassociated because the ProtocolStateActor was stopped normally
[DEBUG][03/11/2020 20:27:13][Thread 0020][akka://JobDispatcherSystem/system/transports/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3A%2F%2FJobDispatcherSystem%40laxmtir01.somedomain.com%3A9901-10] Stopped
[DEBUG][03/11/2020 20:27:15][Thread 0047][akka://JobDispatcherSystem/user/notification-sender-router-pool] now supervising akka://JobDispatcherSystem/user/notification-sender-router-pool/c9
[DEBUG][03/11/2020 20:27:15][Thread 0047][akka://JobDispatcherSystem/user/notification-sender-router-pool] now supervising akka://JobDispatcherSystem/user/notification-sender-router-pool/c10
[DEBUG][03/11/2020 20:27:15][Thread 0016][akka://JobDispatcherSystem/user/notification-sender-router-pool/c9] Started (Cornerstone.JobDispatcherService.NotificationSenderActor)
[DEBUG][03/11/2020 20:27:15][Thread 0027][akka://JobDispatcherSystem/user/notification-sender-router-pool/c10] Started (Cornerstone.JobDispatcherService.NotificationSenderActor)
[DEBUG][03/11/2020 20:27:15][Thread 0027][akka://JobDispatcherSystem/user/notification-sender-router-pool/c10] now watched by [akka://JobDispatcherSystem/user/notification-sender-router-pool#1489572681]
[DEBUG][03/11/2020 20:27:15][Thread 0016][akka://JobDispatcherSystem/user/notification-sender-router-pool/c9] now watched by [akka://JobDispatcherSystem/user/notification-sender-router-pool#1489572681]
[DEBUG][03/11/2020 20:27:15][Thread 0017][akka://JobDispatcherSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobDispatcherSystem%40laxmtir01.somedomain.com%3A9901-10] Stopped
[DEBUG][03/11/2020 20:27:15][Thread 0018][akka://JobDispatcherSystem/system/endpointManager] received AutoReceiveMessage <Terminated>: [akka://JobDispatcherSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobDispatcherSystem%40laxmtir01.somedomain.com%3A9901-10#1708523824] - ExistenceConfirmed=True
[INFO][03/11/2020 20:27:28][Thread 0023][TcpClientHandler (akka://JobDispatcherSystem)] Socket read operation aborted. Connection is about to be closed. Channel [10.5.31.141:57152->10.10.215.82:9901](Id=2608b616)
[DEBUG][03/11/2020 20:27:28][Thread 0026][ActorSystem(JobDispatcherSystem)] Disposing system
[DEBUG][03/11/2020 20:27:28][Thread 0026][ActorSystem(JobDispatcherSystem)] System shutdown initiated
[DEBUG][03/11/2020 20:27:28][Thread 0028][akka://JobDispatcherSystem/user/jobeventstore-updater-router-pool/$a] no longer watched by [akka://JobDispatcherSystem/user/jobeventstore-updater-router-pool#1819656920]
[DEBUG][03/11/2020 20:27:28][Thread 0016][akka://JobDispatcherSystem/user/jobeventstore-reader-router-pool] Stopping
[DEBUG][03/11/2020 20:27:28][Thread 0027][akka://JobDispatcherSystem/user/jobeventstore-reader-router-pool/$a] no longer watched by [akka://JobDispatcherSystem/user/jobeventstore-reader-router-pool#592438905]
[DEBUG][03/11/2020 20:27:28][Thread 0027][akka://JobDispatcherSystem/user/jobeventstore-reader-router-pool/$a] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0046][akka://JobDispatcherSystem/user/jobeventstore-updater-router-pool/$a] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0014][akka://JobDispatcherSystem/user/jobeventstore-updater-router-pool] Stopping
[DEBUG][03/11/2020 20:27:28][Thread 0027][akka://JobDispatcherSystem/user/jobeventstore-reader-router-pool] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0014][akka://JobDispatcherSystem/user/jobeventstore-updater-router-pool] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0005][akka://JobDispatcherSystem/user] Stopping
[DEBUG][03/11/2020 20:27:28][Thread 0050][akka://JobDispatcherSystem/user/notification-sender-router-pool] Stopping
[DEBUG][03/11/2020 20:27:28][Thread 0052][akka://JobDispatcherSystem/user/notification-sender-router-pool/c9] no longer watched by [akka://JobDispatcherSystem/user/notification-sender-router-pool#1489572681]
[DEBUG][03/11/2020 20:27:28][Thread 0051][akka://JobDispatcherSystem/user/notification-sender-router-pool/c10] no longer watched by [akka://JobDispatcherSystem/user/notification-sender-router-pool#1489572681]
[DEBUG][03/11/2020 20:27:28][Thread 0052][akka://JobDispatcherSystem/user/notification-sender-router-pool/c9] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0051][akka://JobDispatcherSystem/user/notification-sender-router-pool/c10] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0052][akka://JobDispatcherSystem/user/notification-sender-router-pool] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0045][akka://JobDispatcherSystem/user/$c] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0047][akka://JobDispatcherSystem/user/$b] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0027][akka://JobDispatcherSystem/user/$a] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0028][akka://JobDispatcherSystem/user] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0046][akka://JobDispatcherSystem/system] received AutoReceiveMessage <Terminated>: [akka://JobtestSystem/user] - ExistenceConfirmed=True
[INFO][03/11/2020 20:27:28][Thread 0017][/system/remoting-terminator] Shutting down remote daemon.
[INFO][03/11/2020 20:27:28][Thread 0017][/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[DEBUG][03/11/2020 20:27:28][Thread 0019][akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0] now watched by [akka://JobtestSystem/temp/h]
[DEBUG][03/11/2020 20:27:28][Thread 0019][akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0] received AutoReceiveMessage <PoisonPill>
[DEBUG][03/11/2020 20:27:28][Thread 0019][akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0] Stopped
[INFO][03/11/2020 20:27:28][Thread 0016][remoting (akka://JobtestSystem)] Remoting shut down
[INFO][03/11/2020 20:27:28][Thread 0017][/system/remoting-terminator] Remoting shut down.
[DEBUG][03/11/2020 20:27:28][Thread 0045][EventStream] subscribing [akka://all-systems/] to channel Akka.Event.Debug
[DEBUG][03/11/2020 20:27:28][Thread 0045][EventStream] subscribing [akka://all-systems/] to channel Akka.Event.Info
[DEBUG][03/11/2020 20:27:28][Thread 0045][EventStream] subscribing [akka://all-systems/] to channel Akka.Event.Warning
[DEBUG][03/11/2020 20:27:28][Thread 0045][EventStream] subscribing [akka://all-systems/] to channel Akka.Event.Error
[DEBUG][03/11/2020 20:27:28][Thread 0017][akka://JobtestSystem/system/remoting-terminator] Stopped
[DEBUG][03/11/2020 20:27:28][Thread 0045][EventStream] Shutting down: StandardOutLogger started
[DEBUG][03/11/2020 20:27:28][Thread 0045][EventStream] unsubscribing [akka://JobtestSystem/system/log1-NLogLogger#1089268832] from all channels
[DEBUG][03/11/2020 20:27:29][Thread 0013][akka://JobtestSystem/system/log1-NLogLogger] Stopped

**Comment by Aaronontheweb** [comment]
We'll look into it, but in the meantime - don't call `Dispose` - `await Terminate` instead.

**Comment by Aaronontheweb** [comment]
As a workaround.

**Comment by huzaifak** [comment]
In case we dont call corodinatedshutdown and just call dispose the below is logged.

[DEBUG][03/11/2020 22:54:53][Thread 0056][EventStream] subscribing [akka://all-systems/] to channel Akka.Event.Debug
[DEBUG][03/11/2020 22:54:53][Thread 0056][EventStream] subscribing [akka://all-systems/] to channel Akka.Event.Info
[DEBUG][03/11/2020 22:54:53][Thread 0056][EventStream] subscribing [akka://all-systems/] to channel Akka.Event.Warning
[DEBUG][03/11/2020 22:54:53][Thread 0056][EventStream] subscribing [akka://all-systems/] to channel Akka.Event.Error
[DEBUG][03/11/2020 22:54:53][Thread 0056][EventStream] Shutting down: StandardOutLogger started
[DEBUG][03/11/2020 22:54:53][Thread 0056][EventStream] unsubscribing [akka://JobtestSystem/system/log1-NLogLogger#302996495] from all channels
[DEBUG][03/11/2020 22:54:53][Thread 0056][EventStream] All default loggers stopped
[DEBUG][03/11/2020 22:54:53][Thread 0017][akka://JobtestSystem/system/remoting-terminator] Stopped
[DEBUG][03/11/2020 22:54:53][Thread 0069][akka://JobtestSystem/system/EventStreamUnsubscriber-1] Stopped
[DEBUG][03/11/2020 22:54:53][Thread 0056][akka://JobtestSystem/system] Stopping
[DEBUG][03/11/2020 22:54:53][Thread 0019][akka://JobtestSystem/system/remote-deployment-watcher] Stopped
[DEBUG][03/11/2020 22:54:53][Thread 0066][akka://JobtestSystem/system/transports] Stopped
[DEBUG][03/11/2020 22:54:53][Thread 0068][akka://JobtestSystem/system/UnhandledMessageForwarder] Stopped
[DEBUG][03/11/2020 22:54:53][Thread 0060][akka://JobtestSystem/system/remote-watcher] Stopped
[DEBUG][03/11/2020 22:54:53][Thread 0018][akka://JobtestSystem/system/endpointManager] Stopped
[DEBUG][03/11/2020 22:54:37][Thread 0019][akka://JobtestSystem/system/endpointManager/endpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-12/endpointReader-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-1] no longer watched by [akka://JobtestSystem/system/endpointManager/endpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-12#1769223200]
[DEBUG][03/11/2020 22:54:37][Thread 0019][akka://JobtestSystem/system/endpointManager/endpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-12/endpointReader-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-1] Stopped
[DEBUG][03/11/2020 22:54:37][Thread 0018][akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901/system/endpointManager/endpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-12] Disassociated [akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901] <- akka.tcp://JobtestSystem@laxmtir1002.somedomain.com:9901
[DEBUG][03/11/2020 22:54:37][Thread 0018][akka://JobtestSystem/system/endpointManager/endpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-12] Stopped
[DEBUG][03/11/2020 22:54:37][Thread 0019][akka://JobtestSystem/system/endpointManager] received AutoReceiveMessage <Terminated>: [akka://JobtestSystem/system/endpointManager/endpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-12#1769223200] - ExistenceConfirmed=True
[DEBUG][03/11/2020 22:54:37][Thread 0045][akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901/system/cluster/core/daemon/heartbeatSender] Cluster Node [akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901] - Heartbeat to [akka.tcp://JobtestSystem@laxmtir1002.somedomain.com:9901]
[INFO][03/11/2020 22:54:37][Thread 0015][Cluster (akka://JobtestSystem)] Cluster Node [akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901] - Shutting down myself
[INFO][03/11/2020 22:54:37][Thread 0015][Cluster (akka://JobtestSystem)] Cluster Node [akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901] - Shutting down...
[INFO][03/11/2020 22:54:37][Thread 0015][Cluster (akka://JobtestSystem)] Cluster Node [akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901] - Successfully shut down
[DEBUG][03/11/2020 22:54:37][Thread 0015][akka://JobtestSystem/system/clusterEventBusListener] received AutoReceiveMessage <PoisonPill>
[DEBUG][03/11/2020 22:54:37][Thread 0066][akka://JobtestSystem/system/cluster/heartbeatReceiver] Stopped
[DEBUG][03/11/2020 22:54:37][Thread 0015][akka://JobtestSystem/system/clusterEventBusListener] Stopped
[DEBUG][03/11/2020 22:54:37][Thread 0066][EventStream] unsubscribing [akka://JobtestSystem/system/clusterEventBusListener#226349228] from all channels
[DEBUG][03/11/2020 22:54:37][Thread 0056][akka://JobtestSystem/system/cluster] Stopping
[DEBUG][03/11/2020 22:54:37][Thread 0026][akka://JobtestSystem/system/cluster/core] Stopping
[DEBUG][03/11/2020 22:54:37][Thread 0027][akka://JobtestSystem/system/cluster/core/daemon] no longer watched by [akka://JobtestSystem/system/cluster/core#206680504]
[DEBUG][03/11/2020 22:54:37][Thread 0027][akka://JobtestSystem/system/cluster/core/daemon] Stopping
[DEBUG][03/11/2020 22:54:37][Thread 0026][akka://JobtestSystem/system/cluster/core/daemon/downingProvider] Stopped
[DEBUG][03/11/2020 22:54:37][Thread 0066][akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901/system/remote-watcher] Unwatching: [akka://JobtestSystem/user/CoreSingletonManagerProxy -> akka.tcp://JobtestSystem@laxmtir1002.somedomain.com:9901/user/CoreSingletonManager/CoreSingletonManager]
[DEBUG][03/11/2020 22:54:37][Thread 0060][akka://JobtestSystem/system/distributedPubSubMediator/SystemEvent] no longer watched by [akka://JobtestSystem/system/distributedPubSubMediator#1558861071]
[DEBUG][03/11/2020 22:54:37][Thread 0066][akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901/system/remote-watcher] Cleanup self watch of [akka.tcp://JobtestSystem@laxmtir1002.somedomain.com:9901/user/CoreSingletonManager/CoreSingletonManager]
[DEBUG][03/11/2020 22:54:37][Thread 0015][akka://JobtestSystem/system/distributedPubSubMediator] Stopping
[DEBUG][03/11/2020 22:54:37][Thread 0028][akka://JobtestSystem/system/cluster/core/publisher] Stopped
[DEBUG][03/11/2020 22:54:37][Thread 0015][akka://JobtestSystem/user/$a] no longer watched by [akka://JobtestSystem/system/distributedPubSubMediator/SystemEvent#14048522]
[DEBUG][03/11/2020 22:54:37][Thread 0063][akka://JobtestSystem/user/CoreSingletonManagerProxy] Stopped
[DEBUG][03/11/2020 22:54:37][Thread 0045][akka://JobtestSystem/system/cluster/core/daemon/heartbeatSender] Stopped
[DEBUG][03/11/2020 22:54:37][Thread 0067][akka://JobtestSystem/user/notification-sender-router-pool/c10] no longer watched by [akka://JobtestSystem/user/notification-sender-router-pool#188147261]
[DEBUG][03/11/2020 22:54:37][Thread 0029][akka://JobtestSystem/user/ddataReplicator] Stopped
[DEBUG][03/11/2020 22:54:37][Thread 0069][akka://JobtestSystem/user/$c] no longer watched by [akka://JobtestSystem/user/ddataReplicator#1291498642]
[DEBUG][03/11/2020 22:54:37][Thread 0059][akka://JobtestSystem/system/distributedPubSubMediator/JobEvent] no longer watched by [akka://JobtestSystem/system/distributedPubSubMediator#1558861071]
[DEBUG][03/11/2020 22:54:37][Thread 0060][akka://JobtestSystem/system/distributedPubSubMediator/SystemEvent] Stopped
[DEBUG][03/11/2020 22:54:37][Thread 0060][akka://JobtestSystem/user/$b] no longer watched by [akka://JobtestSystem/system/distributedPubSubMediator/JobEvent#238200176]
[DEBUG][03/11/2020 22:54:37][Thread 0060][akka://JobtestSystem/user/notification-sender-router-pool/c11] no longer watched by [akka://JobtestSystem/user/notification-sender-router-pool#188147261]
[DEBUG][03/11/2020 22:54:37][Thread 0059][akka://JobtestSystem/system/distributedPubSubMediator/JobEvent] Stopped
[DEBUG][03/11/2020 22:54:37][Thread 0058][EventStream] unsubscribing [akka://JobtestSystem/system/cluster/core/daemon#2128535225] from all channels
[DEBUG][03/11/2020 22:54:37][Thread 0058][akka://JobtestSystem/system/cluster/core/daemon] Stopped
[DEBUG][03/11/2020 22:54:37][Thread 0059][akka://JobtestSystem/system/distributedPubSubMediator] Stopped
[DEBUG][03/11/2020 22:54:37][Thread 0058][akka://JobtestSystem/system/cluster/core] Stopped
[DEBUG][03/11/2020 22:54:43][Thread 0015][akka://JobtestSystem/user/notification-sender-router-pool/c10] received AutoReceiveMessage <PoisonPill>
[DEBUG][03/11/2020 22:54:43][Thread 0015][akka://JobtestSystem/user/notification-sender-router-pool/c10] Stopped
[DEBUG][03/11/2020 22:54:43][Thread 0066][akka://JobtestSystem/system/remote-watcher] received AutoReceiveMessage <AddressTerminated>: akka.tcp://JobtestSystem@laxmtir1002.somedomain.com:9901
[DEBUG][03/11/2020 22:54:43][Thread 0057][akka://JobtestSystem/user/notification-sender-router-pool/c11] received AutoReceiveMessage <PoisonPill>
[DEBUG][03/11/2020 22:54:43][Thread 0057][akka://JobtestSystem/user/notification-sender-router-pool/c11] Stopped
[WARNING][03/11/2020 22:54:43][Thread 0017][remoting (akka://JobtestSystem)] Association to [akka.tcp://JobtestSystem@laxmtir1002.somedomain.com:9901] having UID [1828669042] is irrecoverably failed. UID is now quarantined and all messages to this UID will be delivered to dead letters. Remote actorsystem must be restarted to recover from this situation.
[DEBUG][03/11/2020 22:54:43][Thread 0020][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-2] now supervising akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-2/endpointWriter
[DEBUG][03/11/2020 22:54:43][Thread 0020][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-2] Stopping
[DEBUG][03/11/2020 22:54:43][Thread 0068][akka://JobtestSystem/user/notification-sender-router-pool] now supervising akka://JobtestSystem/user/notification-sender-router-pool/c12
[DEBUG][03/11/2020 22:54:43][Thread 0068][akka://JobtestSystem/user/notification-sender-router-pool] now supervising akka://JobtestSystem/user/notification-sender-router-pool/c13
[DEBUG][03/11/2020 22:54:43][Thread 0019][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-2/endpointWriter] Started (Akka.Remote.EndpointWriter)
[DEBUG][03/11/2020 22:54:43][Thread 0019][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-2/endpointWriter] now watched by [akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-2#1755572140]
[DEBUG][03/11/2020 22:54:43][Thread 0068][akka://JobtestSystem/user/notification-sender-router-pool/c12] Started (Cornerstone.JobDispatcherService.NotificationSenderActor)
[DEBUG][03/11/2020 22:54:43][Thread 0019][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-2/endpointWriter] no longer watched by [akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-2#1755572140]
[DEBUG][03/11/2020 22:54:43][Thread 0068][akka://JobtestSystem/user/notification-sender-router-pool/c12] now watched by [akka://JobtestSystem/user/notification-sender-router-pool#188147261]
[DEBUG][03/11/2020 22:54:43][Thread 0019][akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-2/endpointWriter] Disassociated [akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901] -> akka.tcp://JobtestSystem@laxmtir1002.somedomain.com:9901
[DEBUG][03/11/2020 22:54:43][Thread 0068][akka://JobtestSystem/user/notification-sender-router-pool/c13] Started (Cornerstone.JobDispatcherService.NotificationSenderActor)
[DEBUG][03/11/2020 22:54:43][Thread 0068][akka://JobtestSystem/user/notification-sender-router-pool/c13] now watched by [akka://JobtestSystem/user/notification-sender-router-pool#188147261]
[DEBUG][03/11/2020 22:54:43][Thread 0019][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-2/endpointWriter] Stopped
[INFO][03/11/2020 22:54:43][Thread 0019][akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-2] Removing receive buffers for [akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901]->[akka.tcp://JobtestSystem@laxmtir1002.somedomain.com:9901]
[DEBUG][03/11/2020 22:54:43][Thread 0019][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-2] Stopped
[DEBUG][03/11/2020 22:54:45][Thread 0020][akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0] now supervising akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3A%2F%2FJobtestSystem%4010.10.215.82%3A50716-31
[DEBUG][03/11/2020 22:54:45][Thread 0019][akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3A%2F%2FJobtestSystem%4010.10.215.82%3A50716-31] Started (Akka.Remote.Transport.ProtocolStateActor)
[DEBUG][03/11/2020 22:54:49][Thread 0017][akka://JobtestSystem/system/endpointManager] now supervising akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-13
[DEBUG][03/11/2020 22:54:49][Thread 0017][akka://JobtestSystem/system/endpointManager] received AutoReceiveMessage <Terminated>: [akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-2#1755572140] - ExistenceConfirmed=True
[DEBUG][03/11/2020 22:54:49][Thread 0019][akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901/system/transports/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3A%2F%2FJobtestSystem%4010.10.215.82%3A50716-31] Association between local [tcp://JobtestSystem@0.0.0.0:9901] and remote [tcp://JobtestSystem@10.10.215.82:50716] was disassociated because the ProtocolStateActor was stopped normally
[DEBUG][03/11/2020 22:54:49][Thread 0019][akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3A%2F%2FJobtestSystem%4010.10.215.82%3A50716-31] Stopped
[DEBUG][03/11/2020 22:54:49][Thread 0020][akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0] now supervising akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-32
[DEBUG][03/11/2020 22:54:49][Thread 0017][akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-32] Started (Akka.Remote.Transport.ProtocolStateActor)
[DEBUG][03/11/2020 22:54:49][Thread 0018][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-13] Started (Akka.Remote.ReliableDeliverySupervisor)
[DEBUG][03/11/2020 22:54:49][Thread 0018][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-13] now watched by [akka://JobtestSystem/system/endpointManager#1175942881]
[DEBUG][03/11/2020 22:54:49][Thread 0018][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-13] now supervising akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-13/endpointWriter
[DEBUG][03/11/2020 22:54:49][Thread 0017][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-13/endpointWriter] Started (Akka.Remote.EndpointWriter)
[DEBUG][03/11/2020 22:54:49][Thread 0017][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-13/endpointWriter] now watched by [akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-13#731983595]
[DEBUG][03/11/2020 22:54:52][Thread 0014][ActorSystem(JobtestSystem)] Disposing system
[DEBUG][03/11/2020 22:54:52][Thread 0014][ActorSystem(JobtestSystem)] System shutdown initiated
[DEBUG][03/11/2020 22:54:52][Thread 0026][akka://JobtestSystem/user/jobeventstore-reader-router-pool] Stopping
[DEBUG][03/11/2020 22:54:52][Thread 0063][akka://JobtestSystem/user/jobeventstore-reader-router-pool/$a] no longer watched by [akka://JobtestSystem/user/jobeventstore-reader-router-pool#693265371]
[DEBUG][03/11/2020 22:54:52][Thread 0063][akka://JobtestSystem/user/jobeventstore-reader-router-pool/$a] Stopped
[DEBUG][03/11/2020 22:54:52][Thread 0056][akka://JobtestSystem/user/jobeventstore-reader-router-pool] Stopped
[DEBUG][03/11/2020 22:54:52][Thread 0028][akka://JobtestSystem/user/$c] Stopped
[DEBUG][03/11/2020 22:54:52][Thread 0015][akka://JobtestSystem/user/jobeventstore-updater-router-pool] Stopping
[DEBUG][03/11/2020 22:54:52][Thread 0015][akka://JobtestSystem/user/jobeventstore-updater-router-pool/$a] no longer watched by [akka://JobtestSystem/user/jobeventstore-updater-router-pool#537393750]
[DEBUG][03/11/2020 22:54:52][Thread 0015][akka://JobtestSystem/user/jobeventstore-updater-router-pool/$a] Stopped
[DEBUG][03/11/2020 22:54:52][Thread 0015][akka://JobtestSystem/user/jobeventstore-updater-router-pool/$b] no longer watched by [akka://JobtestSystem/user/jobeventstore-updater-router-pool#537393750]
[DEBUG][03/11/2020 22:54:52][Thread 0015][akka://JobtestSystem/user/jobeventstore-updater-router-pool/$b] Stopped
[DEBUG][03/11/2020 22:54:52][Thread 0015][akka://JobtestSystem/user/jobeventstore-updater-router-pool/$c] no longer watched by [akka://JobtestSystem/user/jobeventstore-updater-router-pool#537393750]
[DEBUG][03/11/2020 22:54:52][Thread 0015][akka://JobtestSystem/user/jobeventstore-updater-router-pool/$c] Stopped
[DEBUG][03/11/2020 22:54:52][Thread 0015][akka://JobtestSystem/user/jobeventstore-updater-router-pool/$e] no longer watched by [akka://JobtestSystem/user/jobeventstore-updater-router-pool#537393750]
[DEBUG][03/11/2020 22:54:52][Thread 0015][akka://JobtestSystem/user/jobeventstore-updater-router-pool/$e] Stopped
[DEBUG][03/11/2020 22:54:52][Thread 0015][akka://JobtestSystem/user/jobeventstore-updater-router-pool] Stopped
[DEBUG][03/11/2020 22:54:52][Thread 0005][akka://JobtestSystem/user] Stopping
[DEBUG][03/11/2020 22:54:52][Thread 0027][akka://JobtestSystem/user/$a] Stopped
[DEBUG][03/11/2020 22:54:52][Thread 0005][akka://JobtestSystem/user/notification-sender-router-pool] Stopping
[DEBUG][03/11/2020 22:54:52][Thread 0027][akka://JobtestSystem/user/notification-sender-router-pool/c13] no longer watched by [akka://JobtestSystem/user/notification-sender-router-pool#188147261]
[DEBUG][03/11/2020 22:54:52][Thread 0005][akka://JobtestSystem/user/notification-sender-router-pool/c12] no longer watched by [akka://JobtestSystem/user/notification-sender-router-pool#188147261]
[DEBUG][03/11/2020 22:54:52][Thread 0005][akka://JobtestSystem/user/notification-sender-router-pool/c12] Stopped
[DEBUG][03/11/2020 22:54:52][Thread 0027][akka://JobtestSystem/user/notification-sender-router-pool/c13] Stopped
[DEBUG][03/11/2020 22:54:52][Thread 0015][akka://JobtestSystem/user/$b] Stopped
[DEBUG][03/11/2020 22:54:52][Thread 0005][akka://JobtestSystem/user/notification-sender-router-pool] Stopped
[DEBUG][03/11/2020 22:54:52][Thread 0015][akka://JobtestSystem/user] Stopped
[DEBUG][03/11/2020 22:54:52][Thread 0015][akka://JobtestSystem/system] received AutoReceiveMessage <Terminated>: [akka://JobtestSystem/user] - ExistenceConfirmed=True
[INFO][03/11/2020 22:54:52][Thread 0017][/system/remoting-terminator] Shutting down remote daemon.
[DEBUG][03/11/2020 22:54:52][Thread 0018][akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0] now supervising akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-33
[INFO][03/11/2020 22:54:52][Thread 0017][/system/remoting-terminator] Remote daemon shut down; proceeding with flushing remote transports.
[DEBUG][03/11/2020 22:54:52][Thread 0019][akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-33] Started (Akka.Remote.Transport.ProtocolStateActor)
[DEBUG][03/11/2020 22:54:53][Thread 0019][akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-32] Stopped
[DEBUG][03/11/2020 22:54:53][Thread 0020][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1001.somedomain.com%3A9901-11] now watched by [akka://JobtestSystem/temp/h]
[DEBUG][03/11/2020 22:54:53][Thread 0019][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-13] now watched by [akka://JobtestSystem/temp/i]
[DEBUG][03/11/2020 22:54:53][Thread 0020][akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-13/endpointWriter] Disassociated [akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901] -> akka.tcp://JobtestSystem@laxmtir1002.somedomain.com:9901
[DEBUG][03/11/2020 22:54:53][Thread 0020][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-13/endpointWriter] Stopped
[DEBUG][03/11/2020 22:54:53][Thread 0019][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-13] received AutoReceiveMessage <Terminated>: [akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-13/endpointWriter#1157874848] - ExistenceConfirmed=True
[INFO][03/11/2020 22:54:53][Thread 0019][akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-13] Removing receive buffers for [akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901]->[akka.tcp://JobtestSystem@laxmtir1002.somedomain.com:9901]
[DEBUG][03/11/2020 22:54:53][Thread 0017][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1001.somedomain.com%3A9901-11/endpointWriter] Stopping
[DEBUG][03/11/2020 22:54:53][Thread 0020][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1001.somedomain.com%3A9901-11/endpointWriter/endpointReader-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1001.somedomain.com%3A9901-1] no longer watched by [akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1001.somedomain.com%3A9901-11/endpointWriter#52898772]
[DEBUG][03/11/2020 22:54:53][Thread 0020][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1001.somedomain.com%3A9901-11/endpointWriter/endpointReader-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1001.somedomain.com%3A9901-1] Stopped
[DEBUG][03/11/2020 22:54:53][Thread 0017][akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1001.somedomain.com%3A9901-11/endpointWriter] Disassociated [akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901] -> akka.tcp://JobtestSystem@laxmtir1001.somedomain.com:9901
[DEBUG][03/11/2020 22:54:53][Thread 0017][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1001.somedomain.com%3A9901-11/endpointWriter] Stopped
[DEBUG][03/11/2020 22:54:53][Thread 0017][akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901/system/transports/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3A%2F%2FJobtestSystem%40laxmtir1001.somedomain.com%3A9901-23] Association between local [tcp://JobtestSystem@0.0.0.0:61296] and remote [tcp://JobtestSystem@laxmtir1001.somedomain.com:9901] was disassociated because the ProtocolStateActor was stopped normally
[DEBUG][03/11/2020 22:54:53][Thread 0017][akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3A%2F%2FJobtestSystem%40laxmtir1001.somedomain.com%3A9901-23] Stopped
[DEBUG][03/11/2020 22:54:53][Thread 0020][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1001.somedomain.com%3A9901-11] received AutoReceiveMessage <Terminated>: [akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1001.somedomain.com%3A9901-11/endpointWriter#52898772] - ExistenceConfirmed=True
[INFO][03/11/2020 22:54:53][Thread 0020][akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1001.somedomain.com%3A9901-11] Removing receive buffers for [akka.tcp://JobtestSystem@csod-2ua7252rnd.somedomain.com:9901]->[akka.tcp://JobtestSystem@laxmtir1001.somedomain.com:9901]
[DEBUG][03/11/2020 22:54:53][Thread 0018][akka://JobtestSystem/system/endpointManager] received AutoReceiveMessage <Terminated>: [akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-13#731983595] - ExistenceConfirmed=True
[DEBUG][03/11/2020 22:54:53][Thread 0018][akka://JobtestSystem/system/endpointManager] received AutoReceiveMessage <Terminated>: [akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1001.somedomain.com%3A9901-11#2110614694] - ExistenceConfirmed=True
[DEBUG][03/11/2020 22:54:53][Thread 0019][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-13] Stopped
[DEBUG][03/11/2020 22:54:53][Thread 0020][akka://JobtestSystem/system/endpointManager/reliableEndpointWriter-akka.tcp%3A%2F%2FJobtestSystem%40laxmtir1001.somedomain.com%3A9901-11] Stopped
[DEBUG][03/11/2020 22:54:53][Thread 0017][akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0] now watched by [akka://JobtestSystem/temp/j]
[DEBUG][03/11/2020 22:54:53][Thread 0017][akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0] received AutoReceiveMessage <PoisonPill>
[DEBUG][03/11/2020 22:54:53][Thread 0017][akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0] Stopping
[DEBUG][03/11/2020 22:54:53][Thread 0017][akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0/akkaProtocol-tcp%3A%2F%2FJobtestSystem%40laxmtir1002.somedomain.com%3A9901-33] Stopped
[DEBUG][03/11/2020 22:54:53][Thread 0018][akka://JobtestSystem/system/transports/akkaprotocolmanager.tcp.0] Stopped
[INFO][03/11/2020 22:54:53][Thread 0015][remoting (akka://JobtestSystem)] Remoting shut down
[INFO][03/11/2020 22:54:53][Thread 0017][/system/remoting-terminator] Remoting shut down.
[DEBUG][03/11/2020 22:54:53][Thread 0056][EventStream] subscribing [akka://all-systems/] to channel Akka.Event.Debug
[DEBUG][03/11/2020 22:54:53][Thread 0056][EventStream] subscribing [akka://all-systems/] to channel Akka.Event.Info
[DEBUG][03/11/2020 22:54:53][Thread 0017][akka://JobtestSystem/system/remoting-terminator] Stopped
[DEBUG][03/11/2020 22:54:53][Thread 0056][EventStream] subscribing [akka://all-systems/] to channel Akka.Event.Warning
[DEBUG][03/11/2020 22:54:53][Thread 0056][EventStream] subscribing [akka://all-systems/] to channel Akka.Event.Error
[DEBUG][03/11/2020 22:54:53][Thread 0056][EventStream] Shutting down: StandardOutLogger started
[DEBUG][03/11/2020 22:54:53][Thread 0056][EventStream] unsubscribing [akka://JobtestSystem/system/log1-NLogLogger#302996495] from all channels
[DEBUG][03/11/2020 22:54:54][Thread 0013][akka://JobtestSystem/system/log1-NLogLogger] Stopped

**Comment by huzaifak** [comment]
I think this is not an akka issue i think we were seeing since we were doing the dispose from a callback in case a member leaves the cluster. If i spin a Task from RegisterOnMemberRemoved callback which then performs to restart of akka subsystem things work fine.

Cluster.Get(ActorSubsystem.ActorSystem).RegisterOnMemberRemoved(() =>
                {
                    if (context.Parameters.ClusterRequireMajorityQuorum)    // don't trigger when running in standalone mode
                        {
                            Stop(); // stop akka
                            Task.Delay(context.Random.Next(1000, 10000)).Wait();
                            Start(); // start akka
                        }
                });

**Comment by huzaifak** [comment]
Not a bug seems
