### ISSUE TITLE
Actor loses context in the context of test

### ISSUE THREAD

**Issue by pirovorster** [akkadotnet/akka.net#4823]
When creating a new issue, please make sure the following information is part of your issue description. (if applicable). Thank You!

Pacakages:
- Akka 1.3.17
- Akka.TestKit.NUnit: 1.3.8

OS:
- Windows 10

Issue:

When running in a actor test and using ReceiveAsync the actor loses context.

```
var props = Props.Create(() => new MyActor());
var identity = ActorOfAsTestActorRef<MyActor>(props, TestActor);
var msg=new MyMessage();
identity.Tell(msg);

```
![image](https://user-images.githubusercontent.com/6638988/110622872-b8cd1600-81a4-11eb-9ff3-59d9d24f25cd.png)

This works when the Self.Tell is moved to before the async message, but the code in the msg being send in the image is never received.

I've had similar issues in other tests as well.

**Comment by Aaronontheweb** [comment]
cc @IgorFedchenko - please see if this is related to the bug that we fixed in 1.4.17.

@pirovorster did you mean 1.4.17 or 1.3.17 for your version report?

**Comment by pirovorster** [comment]
@Aaronontheweb - I did mean 1.3.17 (did not realize we are behind). However after upgrading I still get the same results with

Akka 1.4.17
Akka.TestKit.NUnit: 1.3.8

**Comment by pirovorster** [comment]
Thank you for looking into.

**Comment by IgorFedchenko** [comment]
>please see if this is related to the bug that we fixed in 1.4.17

So this is not something related to our recent updates. I will try to build a reproduction spec for this case.

**Comment by pirovorster** [comment]
If you need me to help with the reproduction let me know.

**Comment by pirovorster** [comment]
@IgorFedchenko just following up on this one. We are having to jump through a lot of capturing contexts hacks to get pass these bugs for testing.

**Comment by IgorFedchenko** [comment]
Hi @pirovorster ! I am going to prioritize this :+1:

I was able to create reproduction spec here: https://github.com/akkadotnet/akka.net/pull/4861 . It seems wrong to me too, so I am changing issue label

**Comment by pirovorster** [comment]
Thank you.

**Comment by Aaronontheweb** [comment]
Tacking this onto the 1.4.18 milestone - our next release.

**Comment by pirovorster** [comment]
@Aaronontheweb any news on this 1. I see its been hopping from milestone to milestone.

**Comment by IgorFedchenko** [comment]
@pirovorster @Aaronontheweb I think https://github.com/akkadotnet/akka.net/pull/4861 is ready to merge and should fix this.

**Comment by pirovorster** [comment]
That's great news.

**Comment by Aaronontheweb** [comment]
This might be a duplicate of https://github.com/akkadotnet/akka.net/issues/2491

**Comment by IgorFedchenko** [comment]
Yep, the comments in that issue are looking very similar to what I found during investigation.

**Comment by Aaronontheweb** [comment]
The real solution to this problem would be to refactor the `InternalActorCellKeeper` to use an `AsyncLocal<ActorCell>` to track the "current cell," but that requires a major redesign of the way actors process messages and a lot of internals that will need to be carefully performance tested. I've documented the scope of that work here: https://github.com/akkadotnet/akka.net/issues/5128

In the meantime, I think this can be fixed by making the `ActorTaskScheduler` sub-classable and changing some of the signature methods on it (unfortunately, this probably means a breaking API change.)
