### ISSUE TITLE
ClusterShardRegion of 1.5 Alpha version unable to restart 

### ISSUE THREAD

**Issue by ingted** [akkadotnet/akka.net#6398]
Version of Akka.NET? 1.5 alpha-3
Which Akka.NET Modules? ClusterSharding

**Describe the bug**

When I use this F# script and reference to akka nuget package version 1.5 alpha-3, once I stop the regionshard, I would unable to restart it again.

https://github.com/Horusiath/Akkling/blob/master/examples/cluster-sharding.fsx

**To Reproduce**

After execute the script, execute:
```
system1.Stop fac1.ShardRegion
let fac1 = entityFactoryFor system1 "printer" <| props (actorOf2 behavior)
let entity1 = fac1.RefFor "shard-1" "entity-1"
entity1 <! "hello"
```
This time hello would not appear.

**Expected behavior**
new shard should be created again and works to print hello (1.4.49 works)

**Actual behavior**
The terminated shardregion still hangs there.

**Additional context**

The only workaround so far I have is to remove all specified shardregion in cluster by the following code:
```
let system1 = System.create "cluster-system" (configWithPort 5000)
let cs = ClusterSharding.Get system1

let cdrfi = cs.GetType().GetField("_regions", BindingFlags.Instance ||| BindingFlags.NonPublic)
let cdpfi = cs.GetType().GetField("_proxies", BindingFlags.Instance ||| BindingFlags.NonPublic)

let cdr : ConcurrentDictionary<string, IActorRef> = unbox (cdrfi.GetValue(cs))
let cdp : ConcurrentDictionary<string, IActorRef> = unbox (cdpfi.GetValue(cs))

match cdr.TryRemove "printer" with
| true, iaref -> printfn "%A" iaref
| _ -> ()
```

**Comment by Aaronontheweb** [comment]
Thanks - cc @zbynek001 any idea if this is by design or a bug?

**Comment by Arkatufus** [comment]
This is by design, shard region actors are NOT supposed to be killed using `ActorSystem.Stop()`, do so at your own risk.

**Comment by Aaronontheweb** [comment]
This has actually been fixed in #6424 - will come out in the next beta release of Akka.NET v1.5 (probably tomorrow.)

**Comment by Arkatufus** [comment]
Stopping shard region actor is still not recommended, this can introduce unforseen consequences.
